apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name }}-deployment
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: remodelingApp3
  template:
    metadata:
      labels:
        app: remodelingApp3
    spec:
      containers:
      - name: remodeling-container
        image: s410071012/remodeling_platform3:{{ .Values.deployment.image.tag }}
        command: ["/bin/sh"]
        args: ["-c", "while true; do python3 /home/jovyan/train-code/train.py;sleep 3000;done"]
        ports:
        - containerPort: 3900
        imagePullPolicy: {{ .Values.deployment.pullPolicy }}
        volumeMounts:
        - name: test-volume
          mountPath: /home/jovyan/my-model
      volumes:
      - name: test-volume
        hostPath:
          path: /downloads3
          type: Directory
